export const TOGGLE_BASKET = "TOGGLE_BASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const UPDATE_BASKET_QUANTITY = "UPDATE_BASKET_QUANTITY";

export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const ADD_MULTIPLE_TO_BASKET = "ADD_MULTIPLE_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";